### PR TITLE
Port To Python 3

### PR DESCRIPTION
**Pull request by Creatune**
This activity has not been tested yet. I will mark for review once I get a promising output.

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed 27bbfa9.  Please proceed when ready.

**Comment by Creatune** [comment]
How do I fix the pygame error: Event queue full?

**Comment by Creatune** [comment]
I have been trying all day but to no avail.

**Comment by Creatune** [comment]
The activity works now.

**Comment by Creatune** [comment]
Are there any problems that I can fix? (Just wanted to cross check)

**Review by rhl-bthr — APPROVED** [review]
Thanks, Looks good.

**Pull request merged**
