### PR TITLE
Merge flappy with flappy-birds

### PR DESCRIPTION
**Pull request by Dimi20cen**
Merge flappy with flappy-birds

- Add up-arrow key functionality for bird movement
- Refine bird rotation for smoother gameplay
- Implement a moving background for enhanced visuals
- Incorporate flapping wings animation
- Adjust the starting point of bottom pipes for better visuals
- Enhance collision detection, using masks, for increased precision
- Introduce a sound effect upon collision, with the bird falling to the ground
- Tweak the points sound effect timing for improved feedback
- Update the game font and add an outline, to resemble the original Flappy Bird
- Replace the existing Sugargame file with the latest version
- Add flake8 file

### CODE REVIEW

**Comment by chimosky** [comment]
Haven't looked at the code yet as that's too many changes for just one commit.

Break your changes into different commits, you could group the ones that are related if any.

**Comment by Dimi20cen** [comment]
The order I made the changes wasn't exactly linear. Therefore, breaking the changes up into multiple of commits can't happen without reverse-enginneering it.<br>
That said, if something doesn't work well or doesn't look the part, I'll gladly change it

**Comment by chimosky** [comment]
> The order I made the changes wasn't exactly linear. Therefore, breaking the changes up into multiple of commits can't happen without reverse-enginneering it. That said, if something doesn't work well or doesn't look the part, I'll gladly change it

The order being linear or not doesn't matter, that's not what's in question.
What's in question is breaking up the commit to lots of different commits with the commit messages reflecting what each commit is for, this makes it easier to review and keeps review comments where they should be.

> Therefore, breaking the changes up into multiple of commits can't happen without reverse-enginneering it.

Don't know what you mean by this but breaking up the commit involves resetting the current commit and then simply adding chunks to various commits with the commit message specifying what happens in each chunk.

**Comment by Dimi20cen** [comment]
Replaced by PR number#18

**Comment by Dimi20cen** [comment]
Replaced by PR number #18

**Pull request closed without merging**
