### PR TITLE
v6

### PR DESCRIPTION
**Pull request by Dimi20cen**
Attempted a release

@chimosky @sourabhaa, kindly review

### CODE REVIEW

**Comment by chimosky** [comment]
They're open issues, please fix them first or make sure they no longer exist.

**Comment by Dimi20cen** [comment]
I didn't use any of the code from flappy-birds activity, so issues from flappy-bird activity shouldn't be present in flappy. Will try to reproduce though

**Comment by Dimi20cen** [comment]
I made a comment in each issue, those issues are not present in flappy

**Comment by chimosky** [comment]
Alright, thanks!

**Pull request merged**
