### PR TITLE
Fix Python GI API version warning

### LINKED ISSUE #3: Python GI API version warning
@zeecoder606, this warning appears;

```
/home/guest/Activities/Flappy.activity/activity.py:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

### PR DESCRIPTION
**Pull request by santiacq**
Fixes https://github.com/sugarlabs/flappy/issues/3
Google Code-In task: https://codein.withgoogle.com/dashboard/task-instances/6747761502322688/

### CODE REVIEW

**Comment by iamutkarshtiwari** [comment]
@quozl Ping

**Comment by quozl** [comment]
Nak.  Is more change than required by the issue.  The versions of `Rsvg` and `SugarExt` were not necessary on my system; on what system was it necessary?  These namespaces are not used by Flappy.  If you are seeing these in logs, please check what version of the Sugar Toolkit you are using, and update it, or post a sample log here for discussion.

**Comment by quozl** [comment]
Discussion on IRC resolved that `Rsvg` and `SugarExt` warnings were emitted by Sugar 0.106.1, and have since been fixed in Sugar Toolkit, so they can be removed from this patch, thanks!

**Comment by santiacq** [comment]
As @quozl wrote, those warnings were caused by an outdated version of Sugar. I have removed those from this patch as they are unnecessary.

**Pull request merged**
