### PR TITLE
[Feature]: #5 [Fix]: #4 [Feature]: Multiple [Update]: Sugargame

### PR DESCRIPTION
**Pull request by rhl-bthr**
**Added in this PR:**
 - Feature #5  with three levels
    - Easy: 33% of the standard (wrt speed and acceleration)
    - Medium: 66% of the standard (50% created a sudden change in difficulty from `medium` to `hard`)
    - Hard: 100% of the standard
 - Possibly fixing #4 (Error was not reproduced)
 - Update sugargame to v1.2
 - Fix volume error left during port
 - Set PEP8

**Tested on:**
 - Sugar 0.112, rdesktop, Ubuntu 16.04

@quozl  Kindly review

### CODE REVIEW

**Comment by rhl-bthr** [comment]
**Updated in this PR:**
 - Add binding of `space` key to the same effect as `mouse-click`
 - Reset best score if level is changed

**Comment by rhl-bthr** [comment]
**Seeking suggestion:**
 - Should the difficulty icons set on basis of user's gender ?
   since gender selection is optional now, currently used icons could be set default.

**Doubt:**
`sugar3/profile` doesn't return user gender, and I couldn't find an alternative way to get user gender in an activiity.

**Comment by rhl-bthr** [comment]
**Updated in this PR:**
 - Ability to pause the game
   - Pause game at any moment by pressing `p` or `Escape`
   - Resume by pressing `p`, `Escape`, `Space` or `MouseButton`

**Comment by quozl** [comment]
Re:

> Should the difficulty icons set on basis of user's gender ?

I don't know.

**Pull request merged**
